datasource:
  korea:
    url: jdbc:mysql://localhost:3306/koreadb?userSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 123456
  japan:
    url: jdbc:mysql://localhost:3306/japandb?userSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 123456
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true